disabled_rules:
- comment_spacing # disabled
- custom_rules # disabled
- cyclomatic_complexity # turn on later
- deployment_target # disabled
- duplicate_enum_cases # disabled
- empty_enum_arguments # disabled
- file_length # 600 warning 1300 error
- for_where # disabled
- force_cast # currently disabled turn on eventually
- function_body_length # turn on eventually
- legacy_nsgeometry_functions #disabled
- line_length # see ok values
- operator_whitespace # disabled
- redundant_optional_initialization # disabled
- redundant_string_enum_value # disabled
- shorthand_operator # disabled
- syntactic_sugar # disabled
- trailing_comma # disabled
- trailing_whitespace # disabled
- type_body_length # look after all errors and warnings are fixed
- type_name # disabled
- unused_closure_parameter # disabled
- unused_optional_binding # fix in eventually
- unused_setter_value # fix in eventually
- vertical_whitespace # disabled
- void_function_in_ternary # disabled
- non_optional_string_data_conversion # disabled

opt_in_rules:
- closure_end_indentation
- closure_spacing
- colon
- comma_inheritance
- control_statement
- literal_expression_end_indentation
- explicit_init
- joined_default_parameter
- lower_acl_than_parent
- modifier_order
- non_overridable_class_declaration
- number_separator
- operator_usage_whitespace
- optional_enum_case_matching
- period_spacing
#  - prefer_self_in_static_references # Check this
- prefer_self_type_over_type_of_self
- prefer_zero_over_explicit_init
- redundant_nil_coalescing
- self_binding
- shorthand_optional_binding
- sorted_imports
- test_case_accessibility
- untyped_error_in_catch
- vertical_parameter_alignment_on_call
- vertical_whitespace_closing_braces
- vertical_whitespace_opening_braces
- weak_delegate

excluded:
  - **/Derived

class_delegate_protocol:
    severity: error

closure_parameter_position:
    severity: error

closure_spacing:
    severity: error

colon:
    severity: error

comma:
    severity: error

comma_inheritance:
    severity: error

compiler_protocol_init:
    severity: error

computed_accessors_order:
    severity: error

control_statement:
    severity: error

#cyclomatic_complexity:
#    error: 10
#    ignores_case_statements: true

discouraged_direct_init:
    severity: error

duplicate_conditions:
    severity: error

duplicate_imports:
    severity: error

duplicated_key_in_dictionary_literal:
    severity: error

empty_parameters:
    severity: error

empty_parentheses_with_trailing_closure:
    severity: error

explicit_init:
    severity: error

force_try:
    severity: error

function_parameter_count:
    warning: 6
    error: 6

identifier_name:
    min_length:
        error: 3
    max_length:
        warning: 50
    allowed_symbols: [_]
    validates_start_with_lowercase: off
    excluded: ["^i$", "^j$", "^n$", "^x$", "^y$", "^id$", "^ID$", "^am$", "^pm$", "^AM$", "^PM$", "^up$", "^ok$", "^on$", "^kg$", "^to$", "^rx$", "^cc$", "^dx$", "^dy$", "^V1$", "^V2$", "^url&", "^NO$"]

implicit_getter:
    severity: error

joined_default_parameter:
    severity: error

large_tuple:
    warning: 4
    error: 3

leading_whitespace:
    severity: error

legacy_cggeometry_functions:
    severity: error

legacy_constant:
    severity: error

legacy_constructor:
    severity: error

legacy_hashing:
    severity: error

legacy_random:
    severity: error

literal_expression_end_indentation:
    severity: error

lower_acl_than_parent:
    severity: error

mark:
    severity: error

modifier_order:
    severity: error

multiple_closures_with_trailing_closure:
    severity: error

nesting:
    type_level:
        warning: 2

no_fallthrough_only:
    severity: error

no_space_in_method_call:
    severity: error

non_overridable_class_declaration:
    severity: error

notification_center_detachment:
    severity: error

ns_number_init_as_function_reference:
    severity: error

nsobject_prefer_isequal:
    severity: error

number_separator:
    severity: error
    minimum_length: 6

opening_brace:
    severity: error

operator_usage_whitespace:
    severity: error

optional_enum_case_matching:
    severity: error

orphaned_doc_comment:
    severity: error

period_spacing:
    severity: error

prefer_self_type_over_type_of_self:
    severity: error

prefer_zero_over_explicit_init:
    severity: error

private_unit_test:
    severity: error

private_over_fileprivate:
    severity: error

protocol_property_accessors_order:
    severity: error

reduce_boolean:
    severity: error

return_arrow_whitespace:
    severity: error

redundant_discardable_let:
    severity: error

redundant_nil_coalescing:
    severity: error

redundant_objc_attribute:
    severity: error

redundant_set_access_control:
    severity: error

redundant_void_return:
    severity: error

self_binding:
    severity: error

self_in_property_initialization:
    severity: error

shorthand_optional_binding:
    severity: error

statement_position:
    severity: error

switch_case_alignment:
    severity: error

test_case_accessibility:
    severity: error

trailing_newline:
    severity: error

trailing_semicolon:
    severity: error

#trailing_whitespace:
#    severity: error

unneeded_break_in_switch:
    severity: error

unneeded_override:
    severity: error

unneeded_synthesized_initializer:
    severity: error

unused_enumerated:
    severity: error

untyped_error_in_catch:
    severity: error

vertical_parameter_alignment:
    severity: error

vertical_parameter_alignment_on_call:
    severity: error

vertical_whitespace_closing_braces:
    severity: error

vertical_whitespace_opening_braces:
    severity: error

void_return:
    severity: error

weak_delegate:
    severity: error

xctfail_message:
    severity: error
