disabled_rules: 

line_length: 120

nesting:
    type_level:
        warning: 2

identifier_name:
  excluded:
    - i
    - id
    - URL
    - vc
    - to

cyclomatic_complexity:
  ignores_case_statements: true

large_tuple:
  error: 4

opening_brace:
  allow_multiline_func: true

analyzer_rules:
  - explicit_self
  - unused_import

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - colon
  - comma
  - comma_inheritance
  - control_statement
  - direct_return
  - explicit_init
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - non_overridable_class_declaration
  - number_separator
  - operator_usage_whitespace
  - optional_enum_case_matching
  - period_spacing
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - redundant_self_in_closure
  - redundant_type_annotation
  - self_binding
  - shorthand_optional_binding
  - strong_iboutlet
  - test_case_accessibility
  - toggle_bool
  - trailing_whitespace
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces